config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  #Rutas Libros
  root 'book#index'
  get "libros/todos", to: "book#index"

  get "libros/nuevo", to:"book#new"
  post "libros/crear", to: "book#create"

  get "libros/mostrar/:id", to:"book#show"
  post "libros/borrar/:id", to:"book#delete"
  
  get "libros/editar/:id", to:"book#edit"
  post "libros/update/:id", to:"book#update"

  #Rutas Usuarios Libros
  get "mis-libros/todos", to:"user_book#index"
  post "mis-libros/agregar", to:"user_book#add"
  
  post "mis-libros/borrar/:id", to:"user_book#delete"

  #Rutas Autores
get "autores/todos", to: "author#index"

get "autores/nuevo", to: "author#new"
post "autores/crear", to: "author#create"

get "autores/mostrar/:id", to: "author#show"
post "autores/borrar/:id", to: "author#delete"

get "autores/editar/:id", to: "author#edit"
post "autores/update/:id", to: "author#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    has_many :user_books
    has_many :users, through: :user_books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :user_books
         has_many :books, through: :user_books

end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :delete]
    def index
        @autor = Author.all
    end

    def new
    end

    def create
        parametros = params.require(:author).permit(:name, :string, :year) 
        Author.create(parametros)
        redirect_to action: "index"
    end
     
    def show
        @autor = Author.find(params[:id])
        @libros = Book.where(author_id: params[:id])
    end

    def delete
        @autor = Author.find(params[:id])
        unless @autor.nil?
            if @autor.delete
                redirect_to action: "index"
            end
        end
    end
    
    def edit
        @autor = Author.find(params[:id])
    end
    
    def update
        parametros = params.require(:author).permit(:name, :string, :year)
        @autor = Author.find(params[:id])
        
        if @autor.update(parametros)
            redirect_to action: "index"
        else
            puts "Error"
        end
    end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :delete]
    def index
        #Consulta a todos los libros
        @books = Book.all 
    end

    def new  #Muestra formulario
        @authors = Author.all
        # Author.find()
        # Author.find_by()
        # Author.where()
    end

    def create # Crea un libro
        book_param = params.require(:book).permit(:title, :description, :author_id) 
        Book.create(book_param)
        redirect_to action: "index"
    end
    
    def show
        @book = Book.find(params[:id])
        if @book.nil?
            redirect_to action: "index"
        else
            @autores = Author.where(id: @book.author_id)
        end
    end

    def delete
        @book = Book.find(params[:id])
        unless @book.nil?
            @book.delete
        end
        redirect_to action: "index"
    end

    def edit  # Get
        @book = Book.find(params[:id])
        @authors = Author.all
    end

    def update 
        @book = Book.find(params[:id])
        parametros = params.require(:book).permit(:title, :description, :author_id) 
    
        if @book.update(parametros)
            redirect_to action: "index"
        else
            puts "Error"
         end
    end

end

app/controllers/user_book_controller.rb
class UserBookController < ApplicationController
    before_action :authenticate_user!
    def index
        @books = current_user.books.select("books.id as id_libro,books.title, books.description, user_books.id")
        #@books = current_user.books
    end

    def add
        book_id = params.require(:book).permit(:id)
        book = Book.find(book_id[:id])   
        unless book.nil?
            current_user.books.push(book)
        end     
        redirect_to action: 'index'
    end

    def delete
        @librosUsuario = UserBook.find(params[:id])
        
        if @librosUsuario.nil?
        else
            if @librosUsuario.delete
                redirect_to action: "index"
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/user_book_helper.rb
module UserBookHelper
end

app/views/author/edit.html.erb
<div class="col-8 offset-2" >
    <h1>Editar Autor</h1>
    <form action="/autores/update/<%= @autor.id %>" method="post">
        <%=  hidden_field_tag :authenticity_token, form_authenticity_token%>
        <input type="hidden" name="author[id]" value="<%= @autor.id %>">
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" name="author[name]" class="form-control" value="<%= @autor.name %>">
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text" name="author[string]" class="form-control" value="<%= @autor.string %>">
        </div>
        <div class="form-group">
            <label>Año</label>
            <input type="text" name="author[year]" class="form-control" value="<%= @autor.year %>">
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </div>  
</form>

app/views/author/index.html.erb
<h1>Autores</h1>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Año</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        <% for autor in @autor  %>
         <tr>
            <td><%= autor.name %></td>
            <td><%= autor.string %></td>
            <td><%= autor.year %></td>
            <td>
                <a href="/autores/mostrar/<%= autor.id %>">Ver</a>
            </td>
            <td><a href="/autores/editar/<%= autor.id %>">Editar</a></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/author/new.html.erb
<div class="col-8 offset-2" >
    <h1>Crear Autor</h1>
    <form action="/autores/crear" method="post">
        <%=  hidden_field_tag :authenticity_token, form_authenticity_token%>
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" name="author[name]" class="form-control">
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <input type="text" name="author[string]" class="form-control">
        </div>
        <div class="form-group">
            <label>Año</label>
            <input type="text" name="author[year]" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Agregar</button>
        </div>
    </div>  
</form>

app/views/author/show.html.erb
<div class="card">
    <div class="card-body">
        <h5 class="card-title"><h2><%= @autor.name %></h2></h5>
        <p class="card-text">
            <%= @autor.string %>

            <h5>Libros Escritos</h5>
            <ul class="list-group">
                <% for libro in @libros %>
                    <li class="list-group-item list-group-item-light">
                        <a href="/libros/mostrar/<%= libro.id %>" data-toggle="tooltip" title="<%= libro.description %>">
                            <%= libro.title %>
                        </a>
                    </li>
                <% end %>
            </ul>    
        </p>
        
        <form action="/autores/borrar/<%= @autor.id %>" method="post">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type="submit" class="btn btn-primary">Borrar</button>
        </form>
        
    </div>
</div>

app/views/book/edit.html.erb
<div class="col-8 offset-2">
    <h3>Editar  Libro</h3>

    <form method="post" action="/libros/update/<%= @book.id %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="hidden"  name="book[id]" value="<%= @book.id %>">
       <div class="form-group">
            <label>Nombre</label>
            <br>
            <input type="text" placeholder="Ingrese nombre" name="book[title]" value="<%= @book.title %>" class="form-control">
        </div>
        <div class="form-group">
            <label>Descriptión</label>
            <br>
            <textarea name="book[description]" class="form-control"><%= @book.description %></textarea>
        </div>
        <div class="form-group">
            <select name="book[author_id]" class="form-control">
                <% for  author in @authors %>
                    <option text="<%= author.name %>" value="<%= author.id %>">
                        <%= author.name %>
                    </option>
                <% end %>
            </select>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </div>
    </form>
</div>

app/views/book/index.html.erb
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Título</th>
            <th>Descripción</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <% for book in @books %>
        <tr>
            <td><%= book.title  %></td>
            <td><%= book.description  %></td>
            <td>
                <a href="/libros/mostrar/<%= book.id %>">Ver</a>
            </td>
            <td><a href="/libros/editar/<%= book.id %>">Editar</a></td>
        </tr>
    <% end %>
</table>

app/views/book/new.html.erb
<div class="col-8 offset-2">
    <h3>Crear Libro</h3>
    <form method="post" action="<%= libros_crear_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group">
            <label>Nombre</label>
            <input type="text" placeholder="Ingrese nombre" name="book[title]" class="form-control">
        </div>
        <div class="form-group">
            <label>Descripción</label>
            <textarea name="book[description]" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label>Autor</label>
            <select name="book[author_id]" class="form-control">
                <% for author in @authors %>
                    <option value="<%= author.id  %>" text="">
                        <%= author.name %>
                    </option>
                <% end %>
            </select>
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Crear</button>
        </div>
    </form>
</div>

app/views/book/show.html.erb
<div class="card">
    <div class="card-body">
        <h5 class="card-title"><%= @book.title %></h5>
        <p class="card-text">
            <%= @book.description %>
            <ul class="list-group">
                <% for autor in @autores %>
                    <li class="list-group-item list-group-item-light">
                        <a href="/autores/mostrar/<%= autor.id %>"><%= autor.name %></a>
                    </li>
                <% end %>
            </ul>
        </p>
        
        <form class="form-check form-check-inline" method="post" action="/libros/borrar/<%= @book.id %>">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type="submit" class="btn btn-primary">Borrar</button>
        </form>

        <% if user_signed_in? %>
            <form class="form-check form-check-inline" method="post" action="<%= mis_libros_agregar_path  %>">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <input type="hidden" name="book[id]" value="<%= @book.id %>" >
                <button type="submit" class="btn btn-primary">Agregar Libro al Carrito</button>
            </form>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore > Carol</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>

  </head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" style="border-bottom: #e9e6e6 1px solid;">
    <a class="navbar-brand" href="/">
      <img src="https://www.paraninfo.es/Images/ficha/muestra_digital.png" class="d-inline-block align-top" width="30" height="30" alt="">
      BookStore
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="/mis-libros/todos">Carrito</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Libros
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/libros/todos">Ver Todos</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/libros/nuevo">Nuevo Libro</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Autores
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/autores/todos">Ver todos</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/autores/nuevo">Nuevo Autor</a>
          </div>
        </li>

      <% if user_signed_in? %>
      <li class="nav-item disabled">
          <span class="navbar-text"><%= current_user.email %></span>
      </li>
      <li class="nav-item">
          <a href="<%= destroy_user_session_path %>" class="nav-link" data-method="delete">Cerrar Cesión</a>
      </li>
        <% else %>
      <li class="nav-item">
        <a href="<%= new_user_session_path %>"  class="nav-link">Log In</a>
      </li>
      <li class="nav-item">
        <a href="<%= new_user_registration_path %>" class="nav-link">Registrarse</a>
      </li>
      <% end %>
      </ul>
    </div>
  </nav>

    <div class="container mt-3 mb-5">
      <%= yield %>
    </div>

    <footer class="fixed-bottom bg-secondary text-white p-2">
      <div class="text-center">
        Tienda de libros © 2018
      </div>
    </footer>
  </body>
</html>

app/views/user_book/index.html.erb
<h1>Libros Comprados</h1>
<ul class="list-group">
    <% for book in  @books %>
        <li class="list-group-item">
            <div class="row">
                <div class="col-8">
                    <a href="/libros/mostrar/<%= book.id_libro %>" data-toggle="tooltip" title="<%= book.description %>">
                        <%= book.title %>
                    </a>
                </div>
                <div class="col-4 text-right">
                    <form method="post" action="/mis-libros/borrar/<%= book.id %>">
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <input  class="btn btn-primary" type="submit" value="X" />
                    </form>
                </div>
            </div>
            
        </li>
    <% end %>
</ul>